### NumPy

NumPy stands for Numerical Python.

NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++

It also has functions for working in domain of linear algebra, Fourier transform, and matrices.

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3,4],[5,6,7,8]])    #creating a 2D array using numpy
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
arr.ndim   #The ndim attribute of an array returns the number of dimensions of the array

2

In [4]:
arr.shape   #The shape attribute of an array returns a tuple representing the dimensions of the array

(2, 4)

In [5]:
type(arr)   #The type() function returns the type of an object

numpy.ndarray

In [6]:
from numpy import random    #random module contains various functions for generating random numbers and arrays

In [7]:
x = random.rand()   #It will generates a random float between 0 and 1 using the rand() function from the random module in numpy
print(x)

0.8674708557310432


In [8]:
x = random.randint(100,size=(5))   #It will generates an array of 5 random integers between 0 and 99 using the randint() function from the random module in numpy
print(x)

[96 90 55 60  0]


In [10]:
x.shape   #he shape of this array is (5,), which means it is a 1D array

(5,)

In [11]:
y = random.randint(100, size =(3,5))   #It will generates an array of 15 random integers between 0 and 99 using the randint() function from the random module in numpy
print(y)

[[34 72 91 33  3]
 [13 28  3 60 43]
 [35 79 16 50  5]]


In [13]:
y.shape   #The shape of this array is (3, 5), which means it is a 2D array with 3 rows and 5 columns

(3, 5)

In [14]:
in_arr = np.array([8])
print("input array is ", in_arr)

out_scalar = np.asscalar(in_arr)   #The np.asscalar() function is used to convert an array of size 1 to its scalar equivalent
print("output array", out_scalar)

print(in_arr.item())   #The np.ndarray.item() method copies an element of an array to a standard Python scalar and returns it

input array is  [8]
output array 8
8


C:\Users\Shubham Dodiya\AppData\Local\Temp\ipykernel_784\3737495658.py:4: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scalar = np.asscalar(in_arr)   #The np.asscalar() function is used to convert an array of size 1 to its scalar equivalent


In [18]:
list1 = [1,2,3]
list2 = [[1],
         [2],
         [3]]    #sub-lists

vector1 = np.array(list1)
vector2 = np.array(list2)

print("horizontal")
print(vector1)

print("vertical")
print(vector2)

horizontal
[1 2 3]
vertical
[[1]
 [2]
 [3]]


In [21]:
a = np.matrix('1 2;3 4')    #The np.matrix() function is used to create a matrix from a string or an array-like object
print(a)

[[1 2]
 [3 4]]


In [24]:
b = np.matrix([[5,6,7],[4,6]])   #array-like object
print(b)                         #ValueError because the sub-lists have different lengths(2x3)

[[list([5, 6, 7]) list([4, 6])]]


In [25]:
b = np.matrix([[-6.9,0],[4,6]])   #2x2 
print(b)

[[-6.9  0. ]
 [ 4.   6. ]]


In [26]:
np.zeros(20,dtype=int).reshape(4,5)   #The np.zeros() function is used to create an array of zeros with the specified shape and data type

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
np.ones(20,dtype=int).reshape(4,5)   #same as above, just using ones(1) instead of zeros(0)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
A = 5
B = [[6,7],
     [8,9]]

print(np.dot(A,B))

[[30 35]
 [40 45]]


In [31]:
A = [[6,7],
     [8,9]]
B = [[6,7],
     [8,9]]
print(np.dot(A,B))    #The np.dot() function is used to compute the dot product of two arrays

[[ 92 105]
 [120 137]]


In [32]:
arr = np.array([[1,2,3],[98,60,75],[79,25,48]])
print(arr)
print(np.amin(arr))   #np.amin() returns the minimum value of an array or minimum along the axis (if mentioned)
print(np.amax(arr))   #while np.amax() returns the maximum of an array or maximum along the axis (if mentioned)

[[ 1  2  3]
 [98 60 75]
 [79 25 48]]
1
98


In [33]:
a = np.array([5,6,7])
print(a)
print(np.mean(a))      #average
print(np.median(a))    #median
print(np.std(a))       #standard deviation
print(np.var(a))       #variance

[5 6 7]
6.0
6.0
0.816496580927726
0.6666666666666666


In [34]:
#why we use standard deviation --> 
#if there are outliers can we can know how far outlier is far frpm z-test

In [37]:
data = [32,36,46,47,56,69,75,79,79,88,89,91,92,93,96,97,101,105,112,116]

Q1 = np.median(data[:10])    #The first quartile (Q1) is the median of the lower half of the data set 

Q3 = np.median(data[10:])    #while the third quartile (Q3) is the median of the upper half of the data set

print('Q1:',Q1)
print('Q3:',Q3)

IQR = Q3-Q1   #The interquartile range (IQR) is defined as Q3 - Q1
print('IQR:',IQR)

Q1: 62.5
Q3: 96.5
IQR: 34.0


In [38]:
len(data)   #length of data set

20

In [39]:
data.sort()   #sorts the list data in ascending order
print(data)

[32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92, 93, 96, 97, 101, 105, 112, 116]


### Case Study

In [40]:
cric_data = np.loadtxt("cric_data.tsv", skiprows=1)

In [44]:
cric_data

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  85.,  12., 224.],
       [ 10.,  18.,  63., 161.],
       [ 11.,   4., 107., 276.],
       [ 12.,   7.,  76., 283.],
       [ 13.,  37.,   4., 297.],
       [ 14.,  14.,   5., 139.],
       [ 15.,   0.,  33., 224.],
       [ 16.,   4.,   7., 178.],
       [ 17.,   0.,   0.,   0.],
       [ 18.,  21.,  36., 193.],
       [ 19.,   1.,  66., 231.],
       [ 20.,  62.,   0., 134.],
       [ 21.,   0., 123., 246.],
       [ 22., 138.,  39., 299.],
       [ 23.,  38.,   9., 242.],
       [ 24.,   2.,  11., 214.],
       [ 25.,  46.,  14., 152.],
       [ 26.,  65.,   0., 104.],
       [ 27.,   0.,   0.,   4.],
       [ 28.,  39.,  26., 155.],
       [ 29.,  48.,   4., 168.],
       [ 3

In [45]:
cric_data.shape

(225, 4)

In [46]:
Sachin = cric_data[:,1]
Dravid = cric_data[:,2]
India = cric_data[:,3]

In [51]:
Sachin

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
         4.,   7.,  37.,  14.,   0.,   4.,   0.,  21.,   1.,  62.,   0.,
       138.,  38.,   2.,  46.,  65.,   0.,  39.,  48., 141.,  62.,  12.,
         1.,  41.,  11.,   3., 186.,  11.,  27.,  27.,  51.,  18.,  32.,
       146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,   2.,  28.,
         6., 123., 120.,   7.,   3.,   0.,  81.,   2.,  54., 122.,   4.,
        14.,   0., 100.,  15.,   0.,  57.,  99.,  37.,  38.,  32.,  21.,
        32.,  40.,   0.,   5.,   8.,   5.,   0.,  50.,  30.,  37.,  89.,
         4.,  98.,  83.,  93.,   0.,  52., 152.,   1.,   8.,  93.,  45.,
        26.,   0.,   1.,   0.,  16.,  47.,  89.,   3.,   1.,  53.,  16.,
         0.,  81.,  14.,  78.,   6., 105., 122.,   9.,   8.,  28.,  35.,
        69.,  13.,  97.,  93.,   2.,  36.,  39.,   2.,  29.,  12.,  19.,
        34.,   2., 100.,  44.,  82.,   0.,  79.,   6.,   9.,   8.,  23.,
        93.,  35.,  63.,  74.,   8., 117.,  39.,  4

#### 1) Find the Mean and Median of Sachin, Dravid and India.

In [53]:
def stats(col):
    print('Mean', np.mean(col))
    print('Median', np.median(col))

In [54]:
stats(Sachin)     

Mean 39.87555555555556
Median 27.0


In [55]:
stats(Dravid)

Mean 32.062222222222225
Median 22.0


In [56]:
stats(India)

Mean 220.79555555555555
Median 216.0


#### 2) How many centuries did Sachin and Dravid Score?

In [57]:
np.count_nonzero(Sachin>99)

26

In [58]:
np.count_nonzero(Dravid>99)     

8

#### 3) How many matches did Sachin and Dravid take to reach 1000 runs?

In [63]:
sachin_cumscores = np.cumsum(Sachin)
np.searchsorted(sachin_cumscores, 1000)

29

In [64]:
dravid_cumscores = np.cumsum(Dravid)
np.searchsorted(dravid_cumscores, 1000)

21